// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CustoFarmDalc.Models
{
    public partial class order
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int Amount { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public string ShipAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public double? Shipping { get; set; }
        public string Email { get; set; }
        public byte[] Date { get; set; }
        public byte OrderShipped { get; set; }
        public string TrackingNumber { get; set; }
    }
}