// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CustoFarmDalc.Models
{
    public partial class productcategory
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    }
}