// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CustoFarmDalc.Models
{
    public partial class productoption
    {
        public int ProductOptionID { get; set; }
        public int ProductID { get; set; }
        public int OptionID { get; set; }
        public int? OptionPriceIncrement { get; set; }
        public int OptionGroupID { get; set; }
    }
}