// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CustoFarmDalc.Models
{
    public partial class product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public double Price { get; set; }
        public double Weight { get; set; }
        public string CartDesc { get; set; }
        public string ShortDesc { get; set; }
        public string Image { get; set; }
        public int? CategoryID { get; set; }
        public byte[] UpdateDate { get; set; }
        public double? ProductStock { get; set; }
        public byte? Live { get; set; }
        public byte? Unlimited { get; set; }
        public string Location { get; set; }
    }
}